name: check

on: push

jobs:
  ruff:
    name: ruff
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v2
      - run: uv venv --python 3.12.4
      - run: uv run ruff check src

  mypy:
    name: mypy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v2
      - run: uv venv --python 3.12.4
      - run: uv run mypy -p src --cache-dir=/dev/null --config-file=pyproject.toml
